### ISSUE TITLE
Cannot use boxterm/main.go (dependency 404 not found error)

### ISSUE THREAD

**Issue by kdzlvaids** [zyedidia/terminal#1]
When I tried to use dependency `"j4k.co/terminal"` which is in `boxterm/main.go`, I got an error `404 not found`.

**Comment by zyedidia** [comment]
This project isn't really maintained for standalone use (it is used inside of the micro editor), but I have updated the example code so that it works. Make sure to `go get github.com/zyedidia/pty` as well.
